# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - classifymushroom

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mushroomclassification.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8f5fde0cf72d4c98b5efa8809c10a5f9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e82f0a04770d4407948b3482ce851bcc }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mushroomclassification.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8f5fde0cf72d4c98b5efa8809c10a5f9 }}/mcapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'classifymushroom'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_196feec822d846099d8dc13b688c5daa }}
        images: 'mushroomclassification.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8f5fde0cf72d4c98b5efa8809c10a5f9 }}/mcapp:${{ github.sha }}'